# permissions for end users to edit moduledeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: moduledeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: module-deployment
    app.kubernetes.io/part-of: module-deployment
    app.kubernetes.io/managed-by: kustomize
  name: moduledeployment-editor-role
rules:
- apiGroups:
  - sofaserverless.sofastack.tech
  resources:
  - moduledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sofaserverless.sofastack.tech
  resources:
  - moduledeployments/status
  verbs:
  - get
